#!/bin/bash

# Muestra la humedad, temp max y min del día.
# Geolocalización automática.

sleep 2

tmin=$(curl -s wttr.in/?format=j2 | grep -o '"mintempC": "[0-9]*"' | sed -E 's/[^0-9]//g' | sort -n | head -1)
tmax=$(curl -s wttr.in/?format=j2 | grep -o '"maxtempC": "[0-9]*"' | sed -E 's/[^0-9]//g' | sort -n | tail -1)
hum=$(curl -s wttr.in/?format=j2 | grep "humidity" | sed -E 's/[^0-9]//g')

echo " $tmaxºC   $tminºC   $hum%"
