#!/bin/sh

##############################################################################
#
# Previsualizar distintos tipos de archivos en lf
#
# Marcos Mikolta
#
##############################################################################

case "$1" in
	*.bmp|*.jpg|*.jpeg|*.png|*.xpm)
		chafa -f sixel -s "$2x$3" --animate off --polite on "$1";;
	*.pdf)
		pdftoppm -singlefile -png "$1" | chafa -f sixel -s "$2x$3" --animate off --polite on;;
	*.zip)
		unzip -Z1 "$1";;
	*.7z)
		7zz l "$1";;
	*)
		expand -t 4 "$1";;
esac
