#!/bin/sh

##############################################################################
#
# Previsualizar distintos tipos de archivos en lf
#
# Marcos Mikolta
#
##############################################################################

case $(file --mime-type -Lb "$1") in
	image/*) 
		chafa -f sixel -s "$2x$3" --animate off --polite on "$1";;
	*/pdf)
		pdftoppm -singlefile -r 72 -png "$1" | chafa -f sixel -s "$2x$3" --animate off --polite on;;
	*/x-7z-compressed)
		7zz l "$1";;
	*/zip)
		unzip -l "$1";;
	*/x-rar*)
		unrar l "$1" | tail -n +7;;
	*)
		expand -t 4 "$1";;
esac

