#!/bin/bash

##############################################################################
#
# Muestra un menú con las diferentes conexiones wifi.
#
# Marcos Mikolta
#
##############################################################################

connect_normal() {
	nmcli device wifi connect "$ssid" password "$password"	
}

connect_user() {
	nmcli con add type wifi \
		ifname wlan0 \
		ssid "$ssid" \
		wifi-sec.key-mgmt wpa-eap \
		802-1x.identity "$user" \
		#802-1x.password "$password" \
		802-1x.system-ca-certs yes \
		802-1x.eap peap \
		802-1x.phase2-auth mschapv2
}

passw() {
	password=$($PASSWORD_MENU)
}

notify() {
	case $1 in
		1)
			notify-send -u low "Conexión exitosa" "Conectado a la red $ssid" -i $NOTIFY_ICONS/wifi-solid.svg
		;;
		0)
			notify-send "Error de conexión" "No se ha podido conectar a $ssid" -i $NOTIFY_ICONS/triangle-exclamation-solid.svg
		;;
	esac
}

notify-send "Buscando redes Wifi..." "Espere por favor" -u low
wifi_list=$(nmcli -t --fields "SSID, BARS, SECURITY" device wifi list | grep '▆')

selected="$(printf "$wifi_list" | awk -F ':' '{
    ssid = $1; bars = $2; security = $3;

    if (bars ~ /▂▄▆█/) {
        if (security ~ /802.1X/)
            print "󰤪  " ssid;
        else if (security ~ /WPA2/)
            print "󰤨  " ssid;
        else
            print "󰤩  " ssid;
    } else if (bars ~ /▂▄▆_/) {
        if (security ~ /802.1X/)
            print "󰤧  " ssid;
        else if (security ~ /WPA2/)
            print "󰤥  " ssid;
        else
            print "󰤣  " ssid;
    }
}' | tofi --prompt-text='Redes wifi disponibles: ')"
[ -z $selected ] && exit 0

icon=$(echo "$selected" | awk '{print $1}')
ssid=$(echo "$selected" | sed 's/^[^ ]*  //')

# Añadir una condición si la ssid esta guardada en la base de datos.

case "$icon" in
	"󰤪"*|"󰤧"*)
		echo "Seguridad"
		echo "$ssid"
		echo "$password"
	;;
	"󰤨"*|"󰤥"*)
		passw && connect_normal && notify 1 || notify 0
	;;
	"󰤩"*|"󰤣"*)
		echo "Abierta"
		echo "$ssid"
	;;
	*)
		exit 0
	;;
esac
